package net.asere.kotlin.js.dsl.ksp.processor

const val jsClassAnnotationName = "net.asere.kotlin.js.dsl.ksp.annotation.JsClass"
const val jsPropertyAnnotationName = "net.asere.kotlin.js.dsl.ksp.annotation.JsProperty"
const val jsFunctionAnnotationName = "net.asere.kotlin.js.dsl.ksp.annotation.JsFunction"
const val jsDslAnnotationName = "net.asere.kotlin.js.dsl.tag.JsDsl"
const val jsConstructorAnnotationName = "net.asere.kotlin.js.dsl.ksp.annotation.JsConstructor"
const val jsChainOperationName = "net.asere.kotlin.js.dsl.syntax.operational.access.operation.ChainOperation"
const val jsInvocationOperationName = "net.asere.kotlin.js.dsl.syntax.operational.invocation.operation.InvocationOperation"
const val jsObjectName = "net.asere.kotlin.js.dsl.type.obj.JsObject"
const val jsSyntaxName = "net.asere.kotlin.js.dsl.syntax.JsSyntax"
const val jsElementName = "net.asere.kotlin.js.dsl.type.JsElement"
const val jsValueRefName = "net.asere.kotlin.js.dsl.type.reference.JsValueRef"
const val jsReferenceIdName = "net.asere.kotlin.js.dsl.type.reference.ReferenceId"
const val jsPrintableDefinitionName = "net.asere.kotlin.js.dsl.type.definition.JsPrintableDefinition"
const val jsReferenceSyntaxName = "net.asere.kotlin.js.dsl.syntax.JsReferenceSyntax"
const val jsAccessOperationName = "net.asere.kotlin.js.dsl.syntax.operational.access.operation.AccessOperation"
const val jsNullableAnnotationName = "net.asere.kotlin.js.dsl.ksp.annotation.JsNullable"
const val jsInternalApiAnnotationName = "net.asere.kotlin.js.dsl.annotation.InternalApi"
const val jsProvideFunctionName = "net.asere.kotlin.js.dsl.provider.provide"
const val jsDslLibName = "net.asere.kotlin.js.dsl.JsDslLib"
const val jsRegisterFunctionName = "net.asere.kotlin.js.dsl.provider.register"
const val jsKotlinJslDomName = "net.asere.kotlin.js.dsl.dom.KotlinJslDom"
const val jsKotlinJslCoreName = "net.asere.kotlin.js.dsl.KotlinJslCore"
const val jsClassWriterName = "net.asere.kotlin.js.dsl.ksp.processor.writer.JsClassWriter"
const val jsInitConfigName = "net.asere.kotlin.js.dsl.ksp.processor.model.JsInitConfig"